version: "3.1"

services:
  db:
    image: mariadb
    restart: always
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: usama
      MARIADB_PASSWORD: pakistan
      MARIADB_DATABASE: flaskdb
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  flask_blog:
    container_name: "flask-container"
    restart: always
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    command: gunicorn -w 4 -b 0.0.0.0:8000 app:app
